.gitignore
lerna.json
package.json
packages/create-single-spa/bin/create-single-spa.js
packages/create-single-spa/package-lock.json
packages/create-single-spa/package.json
packages/generator-single-spa/package-lock.json
packages/generator-single-spa/package.json
packages/generator-single-spa/src/generator-single-spa.js
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/package.json

This project  will use lerna to maintain a monorepo that allows people to create projects with things like `npm init single-spa --framework=react`

Beginnings of create-single-spa and generator-single-spa

---

packages/create-single-spa/package-lock.json
packages/create-single-spa/package.json
packages/generator-single-spa/package-lock.json
packages/generator-single-spa/package.json

Lerna will automatically npm link packages when you do `npm run bootstrap` if you specify the dependencies correctly. So I added generator-single-spa to create-single-spa's package.json and that makes local dev easier.

Fixing local development

---

lerna.json
package.json
packages/create-single-spa/package.json
packages/create-single-spa/yarn.lock
packages/generator-single-spa/package.json
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/.babelrc
packages/generator-single-spa/src/react/templates/.eslintrc
packages/generator-single-spa/src/react/templates/jest.config.json
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/react/templates/src/main.js
packages/generator-single-spa/src/react/templates/src/root.component.js
packages/generator-single-spa/src/react/templates/src/set-public-path.js
packages/generator-single-spa/src/react/templates/webpack.config.js
packages/generator-single-spa/test/basic.test.js
packages/generator-single-spa/test/react.test.js
packages/generator-single-spa/yarn.lock
yarn.lock

This yeoman generator now implements a maybe full functional react project.

Implementing most of react generator

---

packages/generator-single-spa/package.json
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/yarn.lock

After this PR, doing `npm init single-spa` will work successfully when you choose react as your framework.

Last things to get react working.

---

packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/jest.config.js
packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js
packages/generator-single-spa/src/util-module/templates/jest.config.js
packages/generator-single-spa/test/react.test.js
packages/generator-single-spa/test/util-module.test.js

Using js jest config instead of json. Resolves #16

---

packages/generator-single-spa/src/root-config/templates/webpack.config.js

See related #26 and https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/root-config/templates/package.json#L3

Fix bug where isLocal check in root config failed. Resolves #26

---

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
packages/generator-single-spa/src/vue/generator-single-spa-vue.js

added a check for windows to determine to run 'npx' or 'npx.cmd' for ……child process

add a check for windows

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs

Replace importmap script with placeholder comment

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs

Use unminified versions of systemjs files for local dev

---

packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/root-config/templates/package.json
packages/generator-single-spa/src/util-module/templates/package.json

Rename format script

---

packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/jest.config.js
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/react/templates/src/root.component.test.js
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

Resolves #53 
- Added to React template package.json
- Configured in React template jest.config.js
- Added a very simple test file for root.component

Add jest-dom to React template

---

README.md
packages/create-single-spa/bin/create-single-spa.js
packages/generator-single-spa/package.json
packages/generator-single-spa/src/angular/generator-single-spa-angular.js
packages/generator-single-spa/src/generator-single-spa.js
packages/generator-single-spa/src/vue/generator-single-spa-vue.js
packages/generator-single-spa/yarn.lock

See #56. Also this substantially speeds things up for angular/vue users who already have global installations of their respective CLIs.
I tested all of the following in all frameworks
```sh
create-single-spa
create-single-spa .
create-single-spa app1
create-single-spa --dir app1
```

Customize destination directory and use global vue/angular when possible. Resolves #56

---

.prettierignore
README.md
jest.config.js
package.json
packages/generator-single-spa/src/common-templates/typescript/package.json
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/typescript/package.json
packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js
packages/generator-single-spa/src/util-module/templates/package.json
packages/generator-single-spa/src/util-module/templates/tsconfig.json
packages/generator-single-spa/src/util-module/templates/webpack.config.js
packages/webpack-config-single-spa-ts/lib/webpack-config-single-spa-ts.js
tests/e2e/basic-react.test.js
tests/e2e/js-util-module.test.js
tests/e2e/typescript-react.test.js
tests/e2e/typescript-util-module.test.js
tests/test-helpers.js

Adding typescript support for util modules. See #80.

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/test/root-config.test.js

Fix root config template - Resolves #89.

---

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
packages/generator-single-spa/src/vue/generator-single-spa-vue.js

Fixing global installation of vue/angular in Windows. Resolves #91.

---

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
packages/generator-single-spa/src/vue/generator-single-spa-vue.js

Automatically installing Angular and Vue plugins. Resolves #75.

---

CONTRIBUTING.md
packages/create-single-spa/README.md
packages/generator-single-spa/README.md
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/react/templates/tsconfig.json
packages/generator-single-spa/src/root-config/templates/package.json
packages/generator-single-spa/src/root-config/templates/tsconfig.json
packages/generator-single-spa/src/util-module/templates/package.json
packages/generator-single-spa/src/util-module/templates/tsconfig.json
packages/ts-config-single-spa/README.md
packages/ts-config-single-spa/package.json
packages/ts-config-single-spa/tsconfig.json

Implementing shareable ts-config-single-spa. Resolves #60.

---

packages/create-single-spa/bin/create-single-spa.js

See related https://github.com/single-spa/create-single-spa/issues/100

Adding check for minimum nodejs version

---

packages/generator-single-spa/src/react/generator-single-spa-react.js

See #107, https://single-spa.slack.com/archives/C8R6U7MT7/p1588856020174700, and https://single-spa.slack.com/archives/CLB2VV0UF/p1588712347169400?thread_ts=1588712124.167300&cid=CLB2VV0UF

Fixing playground link for react projects.

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs

Add regenerator runtime to root config. Resolves #112.

---

packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js

This way they don't have to deal with HTTPS certificates.

Encourage using http to start out on the playground.

---

packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

Turning on webpack-dev-server gzip compression. Resolves #108.

---

packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/react/templates/src/main.js

See #96 and https://github.com/single-spa/single-spa-react/releases/tag/v2.14.0

Adding errorBoundary opt to single-spa-react.

---

packages/single-spa-welcome/package.json

Forgot to have it build the application before publishing.

Add prepublishOnly script for single-spa-welcome

---

packages/generator-single-spa/src/common-templates/.babelrc.ejs
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/root-config/templates/package.json
packages/generator-single-spa/src/util-module/templates/package.json
packages/single-spa-welcome/package.json
packages/single-spa-welcome/yarn.lock

Setting babel_env to target current node during tests. Resolves #128.

---

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
packages/generator-single-spa/src/react/generator-single-spa-react.js

Partial work for #94 by adding instant-test instructions for newly generated Angular applications.

Additional console instruction for Angular

---

packages/generator-single-spa/src/root-config/generator-root-config.js

I accidentally removed the install step completely in #160. This adds the install step back in and fixes tests.

Re-add install step to root-config

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs

See related https://github.com/joeldenning/import-map-overrides/pull/36

Add comment instructing the user on how to disable import-map-overrides for specific domains.

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs

See https://github.com/systemjs/systemjs/releases and https://github.com/joeldenning/import-map-overrides/releases

Upgrade systemjs and import-map-overrides

---

packages/generator-single-spa/src/vue/generator-single-spa-vue.js

Resolves #164 
To test, I ran the following variations using the cli (along with selecting Vue as the framework):
- `create-single-spa .` (prompts for projectName, generates in current directory)
- `create-single-spa ..`  (prompts for projectName, generates in parent directory)
- `create-single-spa reporting` (derives projectName, generates in current directory)
- `create-single-spa ./reporting` (derives projectName, generates in current directory)
- `create-single-spa ../reporting` (derives projectName, generates in parent directory)

Prompt for projectName if unable to derive from dir

---

packages/generator-single-spa/src/common-templates/typescript/package.json
packages/generator-single-spa/src/common-templates/typescript/react.package.json
packages/generator-single-spa/src/react/generator-single-spa-react.js

Do not install react types in non-react projects. Resolves #171.

---

LICENSE

See #180. Lerna automatically will copy this license file into all other packages during publish. More info at https://github.com/lerna/lerna/issues/1666

Add license file. Resolves #180.

---

packages/generator-single-spa/src/root-config/generator-root-config.js

See https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.1

single-spa-layout is no longer in beta

---

packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/root-config/templates/webpack.config.js
packages/generator-single-spa/src/util-module/templates/package.json
packages/single-spa-welcome/package.json
packages/webpack-config-single-spa-react/lib/webpack-config-single-spa-react.js
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
packages/webpack-config-single-spa/package.json
packages/webpack-config-single-spa/yarn.lock

See related https://github.com/single-spa/standalone-single-spa-webpack-plugin. Also see https://github.com/react-microfrontends/people which is using the standalone plugin.

Adding standalone mode

---

packages/generator-single-spa/src/angular/generator-single-spa-angular.js

Follow up to #201 and resolves #206, I somehow forgot to import path.

Add missing path import

---

packages/generator-single-spa/src/react/templates/webpack.config.js
packages/generator-single-spa/src/root-config/templates/webpack.config.js
packages/generator-single-spa/src/util-module/templates/webpack.config.js
packages/single-spa-welcome/webpack.config.js
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

Disabling HtmlWebpackPlugin and StandaloneSingleSpaPlugin in prod. Resolves #209

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs

Resolves https://github.com/single-spa/single-spa-vue/issues/66

Adding unsafe-eval to script-src CSP.

---

packages/generator-single-spa/src/root-config/templates/webpack.config.js
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

Disable html generation for root configs. Resolves #222.

---

packages/webpack-config-single-spa-ts/lib/webpack-config-single-spa-ts.js

See https://github.com/single-spa/create-single-spa/commit/83c057d0797161fc6e5a6cef0fdd86d35d5e4ba7#r45068446 which pointed out the issue (thanks @nilzona!)

Remove duplicate definition of merge function.

---

packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/package.json
packages/generator-single-spa/src/react/templates/src/main.js
packages/generator-single-spa/src/react/templates/src/set-public-path.js
packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js
packages/generator-single-spa/src/util-module/templates/package.json
packages/generator-single-spa/src/util-module/templates/src/main.js
packages/generator-single-spa/src/util-module/templates/src/set-public-path.js
packages/single-spa-welcome/package.json
packages/single-spa-welcome/src/single-spa-welcome.js
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
packages/webpack-config-single-spa/package.json
packages/webpack-config-single-spa/yarn.lock

See 1.x equivalent PR https://github.com/single-spa/create-single-spa/pull/223

Switch to public path as a webpack plugin.

---

packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

fix: webpack resolve extension issue #241

---

packages/generator-single-spa/src/root-config/templates/webpack.config.js

Treat `isLocal` as a boolean. Resolves #250.

---

packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs

Fixed issue where duplicate versions of the import map overrides were used
Upgraded dependencies

Fixed issue where duplicate versions of the import map overrides were used

---

packages/generator-single-spa/src/react/templates/package.json
packages/single-spa-welcome/package.json
packages/single-spa-welcome/yarn.lock

See https://github.com/single-spa/single-spa-react/issues/103 which reminded me we haven't upgraded single-spa-react here yet.

Upgrade single-spa-react to v4

---

packages/generator-single-spa/src/root-config/templates/package.json
packages/webpack-config-single-spa/package.json
packages/webpack-config-single-spa/yarn.lock

Remove unneeded version of html-webpack-plugin. Resolves #261.

---

.changeset/lazy-impalas-prove.md
packages/generator-single-spa/src/root-config/generator-root-config.js
packages/generator-single-spa/src/root-config/templates/.eslintrc
packages/generator-single-spa/src/root-config/templates/.eslintrc.ejs

Use eslint-config-ts-important-stuff in root configs. Resolves #273.

---

.changeset/wicked-years-tan.md
packages/generator-single-spa/src/version-update-check.js
packages/generator-single-spa/test/root-config.test.js
packages/generator-single-spa/test/version-update-check.test.js

Fix semver check. Resolves #285.

---

.changeset/nine-apes-admire.md
packages/generator-single-spa/src/root-config/templates/src/index.ejs
packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs

Changes made due to issues found here: https://github.com/single-spa/create-single-spa/issues/213
add NoScript tag to HTML templates

fix: noscript tag

---

.changeset/many-flies-tan.md
CONTRIBUTING.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
pnpm-lock.yaml

Support for entry files with extension other than .js. Resolves #305

---

.changeset/lemon-walls-deny.md
.github/workflows/build-and-test.yml
package.json
packages/generator-single-spa/src/common-templates/typescript/typescript.package.json
packages/generator-single-spa/test/basic.test.js
packages/generator-single-spa/test/react.test.js
packages/generator-single-spa/test/root-config.test.js
packages/generator-single-spa/test/svelte.test.js
packages/generator-single-spa/test/util-module.test.js
pnpm-lock.yaml
tests/test-helpers.js

See https://github.com/single-spa/create-single-spa/issues/309#issuecomment-885945468

Upgrade webpack-config-single-spa-ts. Resolves typescript issues.

---

.changeset/happy-frogs-jump.md
.pnpm-debug.log
packages/webpack-config-single-spa/package.json
pnpm-lock.yaml

See related https://github.com/single-spa/standalone-single-spa-webpack-plugin/releases/tag/v3.0.0

Upgrade to standalone-single-spa-webpack-plugin@3

---

.changeset/odd-paws-wink.md
packages/generator-single-spa/src/generator-single-spa.js
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/util-module/generator-react-util-module.js
packages/generator-single-spa/test/util-module.test.js
pnpm-lock.yaml
tests/create-fixtures.js
tests/e2e/util-react-js-webpack.test.js
tests/e2e/util-react-ts-webpack.test.js
tests/test-helpers.js

Support for React utility microfrontends. Resolves #264

---

.changeset/young-grapes-call.md
packages/generator-single-spa/src/common-templates/typescript/typescript.package.json

Resolves #318, this was a problem with the latest release.

Upgrade to ts-config-single-spa@3

---

.changeset/wise-birds-lick.md
packages/generator-single-spa/src/common-templates/babel.config.json.ejs

I noticed some missing quotes in the generated babel config, added those.

Added missing quotes in the babel config

---

.changeset/cyan-years-cross.md
packages/generator-single-spa/src/util-module/templates/util-module.package.json
pnpm-lock.yaml

Fix package manager used in util module build script. Resolves #329.

---

.changeset/loud-knives-tap.md
packages/webpack-config-single-spa/package.json
pnpm-lock.yaml

Remove dependency on unused-files-webpack-plugin. Resolves #334.

---

.changeset/silent-apes-drive.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
pnpm-lock.yaml

Resolves #337 - this adds support for css modules but not for sass. Sass could be discussed in a future issue or PR

Support for CSS modules

---

.changeset/forty-beans-prove.md
.changeset/nasty-clocks-play.md
.github/workflows/build-and-test.yml
packages/single-spa-web-server-utils/__mocks__/import-map-overrides.js
packages/single-spa-web-server-utils/__mocks__/node-fetch.js
packages/single-spa-web-server-utils/jest.config.js
packages/single-spa-web-server-utils/lib/import-map-poller.js
packages/single-spa-web-server-utils/lib/import-map-poller.test.js
packages/single-spa-web-server-utils/package.json
pnpm-lock.yaml

See #342. I pair programmed this with @qirhi so am planning on merging and publishing shortly

Add clearAllIntervals and reset. Fix unhandled promise rejection. Resolves #342

---

.changeset/mighty-scissors-grow.md
packages/single-spa-web-server-utils/lib/single-spa-web-server-utils.js

Expose new apis from single-spa-web-server-utils.

---

.changeset/fuzzy-taxis-fold.md

Adding the missing changeset so I can publish these changes.

chore: adding changeset

---

.changeset/beige-points-rush.md
.changeset/nasty-eggs-visit.md
.husky/pre-commit
packages/generator-single-spa/src/react/templates/react.package.json
packages/generator-single-spa/src/root-config/templates/root-config.package.json
packages/generator-single-spa/src/root-config/templates/src/root-config.ejs
packages/generator-single-spa/src/util-module/templates/util-module.package.json
packages/single-spa-welcome/package.json
packages/webpack-config-single-spa/package.json
pnpm-lock.yaml

See https://github.com/single-spa/standalone-single-spa-webpack-plugin/releases/tag/v4.0.0. Also fixing the build and tests by upgrading webpack and fixing typescript root configs

Upgrade standalone plugin to v4

---

packages/generator-single-spa/src/root-config/templates/src/root-config.ejs

fix types error in boilerplate

---

.changeset/hip-radios-act.md
packages/generator-single-spa/src/root-config/templates/src/root-config.ejs

This is a redo of https://github.com/single-spa/create-single-spa/pull/406, with a changeset so that the publish process can be done normally

Fix typescript error in generated root config

---

.changeset/calm-lions-matter.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

See https://webpack.js.org/guides/public-path/#automatic-publicpath

Use webpack auto public path for native ES modules

---

.changeset/clean-drinks-hide.md
.changeset/thin-actors-rhyme.md
packages/generator-single-spa/src/react/generator-single-spa-react.js
packages/generator-single-spa/src/react/templates/typescript/typescript-react.package.json
pnpm-lock.yaml

Fix react typescript package.json. Resolves #421

---

.changeset/tall-islands-remain.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

Disable hot reloading when using native modules

---

.changeset/tasty-knives-compete.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js

See related https://github.com/react-microfrontends/people/issues/37

Disable standalone mode unless explicitly set. Update isProduction check for latest webpack

---

.changeset/witty-buses-warn.md
packages/generator-single-spa/src/angular/generator-single-spa-angular.js

#449 - While I can't seem to find the root cause of the issue, I believe it's at least worthy of including a log in case the process for creating an Angular app just exits out of nowhere.

Added more console logs for failed Angular scaffolding #449

---

.changeset/purple-hounds-switch.md
packages/generator-single-spa/src/vue/generator-single-spa-vue.js

#449 - While I can't seem to find the root cause of the issue, I believe it's at least worthy of including a log in case the process for creating a Vue app just exits out of nowhere.

Added more console logs for failed Vue scaffolding #449

---

.changeset/hot-parents-fail.md
packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
packages/webpack-config-single-spa/package.json
pnpm-lock.yaml

Upgrade standalone-single-spa-webpack-plugin for ESM. Resolves #452

---

.changeset/mean-drinks-repeat.md
packages/webpack-config-single-spa/package.json
pnpm-lock.yaml

See related https://github.com/single-spa/create-single-spa/issues/454

Downgrade standalone-single-spa-webpack-plugin
