packages/generator-single-spa/src/generator-single-spa.js
This sets things up for us to implement a generator for single-spa root configs and also for raw in-browser modules intended for creating styleguides, api caches, etc.
```js
npm init single-spa -- --moduleType ss-app-parcel --framework react
```
=> Adding prompts and options for generating root configs and raw in-browser modules

packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/react/templates/.prettierignore, packages/generator-single-spa/src/react/templates/package.json, packages/generator-single-spa/src/root-config/generator-root-config.js, packages/generator-single-spa/src/root-config/templates/.prettierignore, packages/generator-single-spa/src/root-config/templates/package.json, packages/generator-single-spa/test/react.test.js, packages/generator-single-spa/test/root-config.test.js
These were fixes I discovered when running create-single-spa on the react microfrontends example. See related https://github.com/react-microfrontends/nav-bar/pull/2 and https://github.com/react-microfrontends/root-config/pull/1
=> Small fixes to react and root config generators

packages/generator-single-spa/src/angular/generator-single-spa-angular.js, packages/generator-single-spa/src/generator-single-spa.js, packages/generator-single-spa/src/vue/generator-single-spa-vue.js
This assumes global installation of angular cli or vue cli when you use create-single-spa. But that seems to me to be a reasonable expectation?
=> Adding support for Vue and Angular CLIs

packages/generator-single-spa/src/angular/generator-single-spa-angular.js, packages/generator-single-spa/src/vue/generator-single-spa-vue.js
Resolves #18.
- create-single-spa always works now
- create-single-spa ignores a global yarn or pnpm installation of angular and vue clis
=> Using npx to execute vue and angular clis

packages/generator-single-spa/src/root-config/generator-root-config.js, packages/generator-single-spa/src/root-config/templates/src/root-config.js
Issue: When running npx create-single-spa and going down the root config path the application does not work out of the box as it implies. 
Solution:
Hard code navbar to be the same as is listed in the given import-map.
=> Updated root-config.js so that the template will work out of the box.

packages/generator-single-spa/src/react/templates/.babelrc, packages/generator-single-spa/src/react/templates/package.json, packages/generator-single-spa/src/root-config/templates/.babelrc, packages/generator-single-spa/src/root-config/templates/package.json, packages/generator-single-spa/src/util-module/templates/.babelrc, packages/generator-single-spa/src/util-module/templates/package.json
See #17. This avoids the `regeneratorRuntime` problems and also saves bundle size
=> Adding babel plugin transform runtime. Resolves #17.

packages/generator-single-spa/src/root-config/templates/src/index.ejs
Allow for local https development - you need https when overriding the js file on deployed envs, but it's annoying to not be able to load up the js file from your local html file because it assumes https instead of http.
=> Allow for local https development

packages/generator-single-spa/src/react/templates/src/set-public-path.js, packages/generator-single-spa/src/util-module/templates/src/set-public-path.js
I've seen a few questions about asking why the CLI generates this file
https://single-spa.slack.com/archives/C8R6U7MT7/p1586204715291500
and a few I've had internally at workfront. I just wanted to discuss if we should add _something like_ this to help answer some of those questions
=> exploring adding an explanitory comment to the file

packages/generator-single-spa/src/root-config/templates/package.json
`eslint src` doesn't work in typescript projects, but `yarn lint` does
=> Fixing issue with root config pre-commit

packages/generator-single-spa/src/root-config/templates/src/index.ejs
Best for organizations not to always use the latest version
=> Pinning systemjs and import-map-overrides versions

packages/generator-single-spa/src/root-config/templates/src/root-config.js
urlRerouteOnly was introduced in https://github.com/single-spa/single-spa/releases/tag/v5.2.0 and is something I think could make sense to turn on by default as a major release of single-spa. For now, though, we can just turn it on by default in the CLI's generated files
=> Making urlRerouteOnly the default for root configs

packages/generator-single-spa/src/root-config/templates/src/index.ejs
See #23. cc @filoxo @Sauloxd. This has been broken for a few weeks now so I figure it would be good to get this merged in and published even if we end up making it fancier later.
=>  Adding shared dependencies import map to root config. Resolves #23. 

packages/generator-single-spa/src/root-config/generator-root-config.js
tsconfig.json files should not be added to javascript projects.
=> Removing tsconfig from js root configs

packages/generator-single-spa/src/root-config/templates/webpack.config.js
These options are already enabled in webpack-config-single-spa, which is now used by root-configs.
=> Removing redundant root config webpack config options.

packages/webpack-config-single-spa-ts/lib/webpack-config-single-spa-ts.js
See #87. When running webpack bundle analyzer, we don't need to check the types.
=> Disabling ForkTsCheckerWebpackPlugin during analyze. Resolves #87.

packages/generator-single-spa/src/react/templates/.prettierignore, packages/generator-single-spa/src/root-config/templates/.prettierignore, packages/generator-single-spa/src/util-module/templates/.prettierignore, packages/single-spa-welcome/.prettierignore
`yarn-error.log` is created when yarn install or yarn scripts fail. That file cannot be processed by prettier and should be ignored.
=> Ignoring yarn-error.log in prettier.

packages/generator-single-spa/src/root-config/templates/src/index.ejs
Resolves #95 
I used the same url for zone.js as used in the documentation here: https://single-spa.js.org/docs/ecosystem-angular/#zonejs
=> Add comment regarding zone.js for Angular applications

packages/generator-single-spa/src/common-templates/typescript/package.json, packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/react/templates/typescript/package.json
This is my attempt at fixing the problem in #139
I have tried with creating a new project and it indeed works for the utils module
When I run tests I have a problem with the package.json that I modified.
```
yarn run v1.22.4
$ jest
Error: Cannot parse /Users/spicciani/dev/microfrontend/create-single-spa/packages/generator-single-spa/src/util-module/templates/package.json as JSON: Unexpected token < in JSON at position 1033
at Object.worker (/Users/spicciani/dev/microfrontend/create-single-spa/node_modules/jest-haste-map/build/worker.js:146:13)
at execFunction (/Users/spicciani/dev/microfrontend/create-single-spa/node_modules/jest-worker/build/workers/processChild.js:183:17)
at execHelper (/Users/spicciani/dev/microfrontend/create-single-spa/node_modules/jest-worker/build/workers/processChi …
```
=> fix eslint issue with typescript. Resolves #139

packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js, packages/generator-single-spa/src/util-module/templates/.eslintrc, packages/generator-single-spa/src/util-module/templates/.eslintrc.ejs
fixes issue where generating util-module with typescript enabled does not have `no-undef` rule via `eslint-config-ts-important-stuff`
=> fix: util-module eslint config

packages/generator-single-spa/package.json, packages/generator-single-spa/src/generator-single-spa.js, packages/generator-single-spa/src/version-update-check.js, packages/generator-single-spa/test/version-update-check.test.js
Resolves #142 
Below is a screenshot of what the terminal message with colors when an outdated version is detected.
I decided last minute to add the underline styling (to help distinguish from the rest of the prompt) after I took the above screenshot.
Feedback: 
- Should there be some sort of flag or config we can add to silence this message? 
- ~~I can't find a good way to test this... should I maybe move it into an external module to simplify testing?~~ I did move these into an external module with some corresponding tests.
=> Check and notify user if a newer version is available

packages/generator-single-spa/src/common-templates/gitignore, packages/single-spa-welcome/.gitignore
Noticed this while working with a client - .DS_Store aren't gitignored in generated projects.
=> Adding .DS_Store files to gitignores

package.json, packages/generator-single-spa/src/react/templates/package.json, packages/generator-single-spa/src/root-config/templates/package.json, packages/single-spa-welcome/package.json
On Windows, the `npm run format` command doesn't work.
Before fix:
After fix:
=> Fixing "format" script on Windows.

packages/generator-single-spa/src/root-config/generator-root-config.js
This change adds messaging after adding single-spa-layout to direct people to GitHub to report issues. While doing this, I noticed that single-spa-layout was being installed even if not using it and causing an extra `install` step, so I've fixed that by extending the package.json instead of calling `install`.
=> Add layout issues link

packages/generator-single-spa/src/react/templates/package.json, packages/generator-single-spa/src/root-config/templates/src/index.ejs, packages/generator-single-spa/src/root-config/templates/src/layout/index.ejs, packages/generator-single-spa/src/util-module/templates/package.json, packages/single-spa-welcome/package.json, packages/single-spa-welcome/yarn.lock
Both libraries have IE11 fixes, and always good to keep them all up-to-date. See https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.1.2
=> Upgrading single-spa and systemjs-webpack-interop.

packages/generator-single-spa/src/vue/generator-single-spa-vue.js
Resolves #173 . Vue app generation silently fails because `dir` is an empty string if a non-relative dir/path is provided. This change resolves dir before parsing, which should guarantee that dir is not an empty string but rather a full path.
=> Fix: Vue app generation silently fails

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
Remove validateSingleSpaDependency since it is resolved as part of single-spa-angular install. This was useful before https://github.com/single-spa/single-spa-angular/pull/193 was merged but that code was released in [single-spa-angular@4.2.0](https://github.com/single-spa/single-spa-angular/releases/tag/v4.2.0). 
Removing this check should resolve #169 since it should no longer be necessary for create-single-spa to deal with this.
=> Remove validateSingleSpaDependency check

packages/generator-single-spa/src/angular/generator-single-spa-angular.js
Resolves #186 by simply removing the prompt and not passing through the packageManager option to the @angular/cli. I preferred this because 1) it is quite a bit of work to extract out the angular cli version, and 2) should be better for future versions since they may remove or change it (and then c-s-s would be forced to do yet another check).
=> Remove packageManager prompt for Angular apps

packages/single-spa-welcome/src/welcome.css, packages/single-spa-welcome/src/welcome.js
In order to better support single-spa-layout and improve a beginner's experience, I'm adding a feature that detects if a page has single-spa-router and displaying different "next steps" based on that. 
I also made some minor changes to the content to explain that shared dependencies are required for a React application.
=> Feature: dynamically show instructions for single-spa-layout root-configs

packages/generator-single-spa/src/angular/generator-single-spa-angular.js, packages/generator-single-spa/src/vue/generator-single-spa-vue.js
Resolves #193
There are only two instances where we use `'.'` as the dir inside of the framework-specific generators. My suspicion is that the one that causes the bug is the Angular one since it's passed as an arg to the angular/cli, while in the Vue one its used to spawn the command with that cwd. In any case, it seems safer to use resolved paths instead of relative ones.
=> Resolve paths before passing through to commands

packages/generator-single-spa/src/validate-naming.js, packages/generator-single-spa/test/validate-naming.test.js
Resolves #195 by removing the string trimming that happens inside of `validateNaming`, which transforms the input for the validation but does not retain that new value. By removing it, space characters will cause a validation error for `orgName` and `projectName`. In the case of the Vue generator, `dir` with spaces will work but then it will prompt for a `projectName` that does not have spaces.
=> Remove trim behavior in validateNaming

packages/single-spa-web-server-utils/lib/import-map-poller.js
With a consulting client we're starting to use single-spa-web-server-utils to help with inlining the import map into the HTML file (not full SSR though). Since it's not full SSR, the nodeKeyFilter option doesn't matter.
=> Make nodeKeyFilter optional

packages/generator-single-spa/src/generator-single-spa.js
Issue was reported on [Slack](https://single-spa.slack.com/archives/C8R6U7MT7/p1602719152061600).
```sh
$ create-single-spa
(node:66831) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
at SingleSpaGenerator.initializing (/Users/joshua/.config/yarn/global/node_modules/generator-single-spa/src/generator-single-spa.js:43:40)
at Object.<anonymous> (/Users/joshua/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:991:25)
at /Users/joshua/.config/yarn/global/node_modules/run-async/index.js:49:25
at new Promise (<anonymous>)
at /Users/joshua/.config/yarn/global/node_modules/run-async/index.js:26:19
at runLoop.add.once.once (/Users/joshua/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:992:11)
at processImmediate …
```
=> Check that remoteVersion exists before trying versionUpdateCheck

packages/generator-single-spa/package.json, packages/generator-single-spa/yarn.lock
**What's the problem this PR addresses?**
`generator-single-spa` is trying to use `chalk` and `ejs` without declaring them as dependencies which makes it rely on something else in the dependency tree to provide it and the package manger to hoist it to an accesible location neither of which is guaranteed and under [Yarn PnP](https://yarnpkg.com/features/pnp) is not allowed at all.
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
**How did you fix it?**
Add `chalk` and `ejs` as dependencies
=> fix(generator-single-spa): add missing dependency chalk and ejs

packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
I found this when upgrading react-mf/api. Not only is the parser system configuration unnecessary, it actually breaks things in webpack 5 if you try to load json modules.
=> Remove system parser false, as it's the new default in webpack 5.

packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/react/templates/package.json, packages/generator-single-spa/src/react/templates/src/main.js, packages/generator-single-spa/src/react/templates/src/set-public-path.js, packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js, packages/generator-single-spa/src/util-module/templates/package.json, packages/generator-single-spa/src/util-module/templates/src/main.js, packages/generator-single-spa/src/util-module/templates/src/set-public-path.js, packages/single-spa-welcome/package.json, packages/single-spa-welcome/src/single-spa-welcome.js, packages/webpack-config-single-spa/lib/webpack-config-single-spa.js, packages/webpack-config-single-spa/package.json, packages/webpack-config-single-spa/yarn.lock
See https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.2.0 and https://github.com/joeldenning/systemjs-webpack-interop#as-a-webpack-plugin
=> Moving public path to a webpack plugin instead of set-public-path.js

packages/single-spa-welcome/webpack.config.js, packages/single-spa-welcome/yarn.lock
After the switch to using webpack public path as a webpack plugin instead of the set-public-path.js file, it now is looking for a module in the systemjs registry with the name `@single-spa/welcome` which doesn't exist in most import maps.
Since single-spa-welcome isn't using any code splits, I don't think it's necessary to set the public path, so I removed it here.
=> Don't set public path for single-spa-welcome.

.prettierignore, packages/generator-single-spa/src/react/templates/.prettierignore, packages/generator-single-spa/src/root-config/templates/.prettierignore, packages/generator-single-spa/src/svelte/templates/.prettierignore, packages/generator-single-spa/src/util-module/templates/.prettierignore, packages/single-spa-welcome/.prettierignore
See #239. The coverage directory is generated by `jest --coverage` and contains an html report. It is gitignored, but also should be prettierignored
=> Add coverage directory to all prettierignores. Resolves #239.

packages/webpack-config-single-spa-ts/lib/webpack-config-single-spa-ts.js
From [these docs](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#typescript-options):
> If you use the babel-loader, it's recommended to use write-references mode to improve initial compilation time.
Since we use babel-loader, I think this will improve build times. I tested locally and it seems to still work as normal.
=> Improve typescript build times by using write-references.

packages/single-spa-welcome/src/welcome.css, packages/single-spa-welcome/src/welcome.js, packages/single-spa-welcome/yarn.lock
See https://github.com/single-spa/single-spa-layout/issues/116 where the global nature of single-spa-welcome's css caused confusion. Generally people shouldn't be using single-spa-welcome at all after initial creation of the root config, but I think it's easy enough to fix this so that others don't run into the same issue.
=> Scope single-spa-welcome css.

.changeset/strong-camels-obey.md, packages/generator-single-spa/src/root-config/generator-root-config.js
We started it off as false by default because single-spa-layout was new. It's now more mature.
=> Use single-spa-layout by default

.changeset/twelve-shoes-eat.md
To force webpack-config-single-spa-react, webpack-config-single-spa-react-ts, and webpack-config-single-spa-ts to use the latest version of webpack-config-single-spa
=> Upgrade webpack upstream dependencies

.changeset/stupid-mayflies-visit.md, packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js
See #278. pnpm and npm require the extra `--` in the command. When pnpm was added as a new option, this was overlooked.
=> Fix start instructions for pnpm. Resolves #278.

.changeset/seven-windows-attend.md, packages/generator-single-spa/src/react/templates/jest.config.js
Changes made due to issues found here: https://github.com/single-spa/single-spa-react/issues/103
Will not fix existing projects but newly generated projects should work ok now. 
Existing projects can be manually fixed by using the example code @joeldenning provided.
=> fixed generated jest config for react unable to load parcels 

.changeset/lemon-crews-grab.md, jest.config.js, packages/generator-single-spa/src/generator-single-spa.js, packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/react/templates/tsconfig.json, packages/generator-single-spa/src/root-config/generator-root-config.js, packages/generator-single-spa/src/svelte/generator-single-spa-svelte.js, packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js, pnpm-lock.yaml, tests/create-fixtures.js, tests/e2e/react-app-js-webpack.test.js, tests/e2e/react-app-ts-webpack.test.js, tests/e2e/root-config-js-webpack-layout.test.js, tests/e2e/root-config-js-webpack.test.js, tests/e2e/root-config-ts-webpack-layout.test.js, tests/e2e/root-config-ts-webpack.test.js, tests/e2e/svelte-app-js.test.js, tests/e2e/util-module-js-webpack.test.js, tests/e2e/util-module-ts-webpack.test.js, tests/test-helpers.js
The tests have been flaky for a long time due to pnpm install race conditions. This forces all fixture creation to be done upfront without installing the dependencies, then running pnpm install one time (rather than for each test), then running the jest tests. I am hopeful this will fix the flakiness once and for all. Also, it seems to have made the tests faster. The downside is that I couldn't find a way to only create the selected fixtures for the tests rather than all fixtures, and then still have install run at the end. But I think avoiding the flakiness is worth it.
=> Add --skipInstall. Fix tests and typescript react-jsx

.changeset/calm-worms-happen.md, .github/workflows/build-and-test.yml, packages/generator-single-spa/src/react/templates/react.package.json, packages/generator-single-spa/src/root-config/templates/root-config.package.json, packages/generator-single-spa/src/util-module/templates/util-module.package.json, packages/single-spa-welcome/package.json, packages/webpack-config-single-spa/lib/webpack-config-single-spa.js, pnpm-lock.yaml
Resolves https://github.com/single-spa/create-single-spa/issues/309
I'm guessing this would be considered a major release given it'd break for anyone who might still be using `webpack-dev-server` v3.x.x (or anyone who's pinned to a beta release of `webpack-dev-server` v4.0.0-beta(x).
Happy to make any changes, just thought I'd kick off a PR to hopefully save some time in getting this fixed :)
=> Upgrade to latest config from webpack-dev-server v4.0.0-rc.0

.changeset/short-vans-hide.md
See #309 and #310. The changeset in #310 was incorrect because it didn't upgrade generator-single-spa. I think this is only a minor change to generator-single-spa because the API for generator-single-spa hasn't changed.
=> Add changeset for package.json changes in generator-single-spa.

.changeset/chilled-buckets-study.md, packages/generator-single-spa/src/common-templates/typescript/typescript.package.json, packages/generator-single-spa/src/react/generator-single-spa-react.js, packages/generator-single-spa/src/react/templates/react.package.json, packages/generator-single-spa/src/react/templates/tsconfig.json, packages/generator-single-spa/src/root-config/generator-root-config.js, packages/generator-single-spa/src/root-config/templates/root-config.package.json, packages/generator-single-spa/src/root-config/templates/tsconfig.json, packages/generator-single-spa/src/svelte/generator-single-spa-svelte.js, packages/generator-single-spa/src/svelte/templates/svelte.package.json, packages/generator-single-spa/src/util-module/generator-single-spa-util-module.js, packages/generator-single-spa/src/util-module/templates/tsconfig.json, packages/generator-single-spa/src/util-module/templates/util-module.package.json, packages/ts-config-single-spa/tsconfig.json, pnpm-lock.yaml
=> Output typescript declarations during build. Resolves #289.

scripts/upgrade-dependencies.sh
This PR changes the name `ncu` to `npm-check-updates`. While `ncu` is the name of the binary exported by `npm-check-updates`, `ncu` is actually [another package](https://www.npmjs.com/package/ncu).
After this fix, i was able to run the script locally without having `npm-check-updates` installed globally.
=> fix upgrade-dependencies script

.changeset/fast-suns-do.md, packages/webpack-config-single-spa/lib/webpack-config-single-spa.js
I was helping someone in the single-spa Slack who was having issues with conflicting SVG loaders. Our webpack config [includes svgs in the list of images](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L91) to process as resources, so its difficult to define a different loader for SVGs. SVGs are also very commonly imported as React components so this is a valuable usecase to accommodate. Prior to this change, one would need to filter out the problematic rule and the provide their own. 
```js
const { mergeWithCustomize, customizeArray } = require("webpack-merge");
const singleSpaDefaults = require("webpack-config-single-spa-react-ts");
const mergeCustom = mergeWithCustomize({
customizeArray: customizeArray({ …
```
=> Extract svg into own loader for easier overrides

.changeset/small-beds-switch.md, packages/webpack-config-single-spa-ts/package.json, pnpm-lock.yaml
error An unexpected error occurred: "could not find a copy of typescript to link in /app/node_modules/webpack-config-single-spa-ts/node_modules".
Issue: #377
=> fix typescript version error

.changeset/tidy-garlics-try.md, .github/workflows/build-and-test.yml, packages/generator-single-spa/src/react/templates/react.package.json, packages/generator-single-spa/src/root-config/templates/root-config.package.json, packages/generator-single-spa/src/util-module/templates/util-module.package.json, packages/single-spa-welcome/package.json, pnpm-lock.yaml
Fix for the problem described in issue https://github.com/single-spa/create-single-spa/issues/382
NOTE: When running the GitHub actions I had problems with the test step. The problem was that I was using a different version of pnpm on my local. I downgraded to the version previously used in the GitHub actions and could reproduce the problem. With that version of pnpm (6.29.1) my lock file was unstable and it changed when running tests. Also, the tests kept failing. By upgrading pnpm to the latest version (8.6.1) the tests run fine. Due to the update, I had to slightly adjust the commands in the GitHub workflow and add a dev dependency that was missing in the single-spa-welcome app. With these minor changes and adjustments, the GitHub actions workflow runs successfully in my local.
=> Update webpack-cli to 4.10

.changeset/wild-islands-melt.md, packages/single-spa-welcome/package.json, pnpm-lock.yaml
Reported on Slack: @single-spa/welcome dies with the message `SKIP_BECAUSE_BROKEN: renderType “createRoot” did not return a function.`. This updates @single-spa/welcome to use single-spa-react@^6.0.1 since the underlying issue appears to be the same as single-spa/single-spa-react#202.
Verified this fix in a local root config.
=> Update single-spa-react to 6.0.1 for welcome app

.changeset/gentle-ducks-wonder.md, packages/webpack-config-single-spa/lib/webpack-config-single-spa.js, pnpm-lock.yaml
This is a breaking change that changes all create-single-spa projects to default to outputting native ES modules.
=> Default to output native modules. Add outputSystemJS option.
